---
# ====== Application: TEMPLATE ===============================
id: 184279
identification: 
  name: TEMPLATE
  alias: TEMPLATE
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Controle de Acesso - Custom # 204933188634819074619

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Allow from same origin
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_APEXBSB2024

globalization: 
  primary-language: Portuguese (Brazil) (pt-br)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APP_NAME.'

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Início

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Menu Navegação Custom # 81988653409984036594

navigation-bar: 
  implementation: List
  list: Barra de Navegação # 204933478929642074915
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 422
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 81992791859285205264
  identification: 
    name: APP_NAME

  value: 
    static-value: TEMPLATE

component-settings: 
- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 81989205315479837690
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 15537094401716

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 82012848341035841378
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15537094431961

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 82036491265151844805
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15537094457129

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 204933185327627074615
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 15505665198303

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 204933185623832074616
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 15505665198306

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 204933185920988074616
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 15505665198306

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 204933186223730074616
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 15505665198306

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 204933186593678074616
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 15505665198306

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 204933186905759074617
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 15505665198306

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 204933187151794074617
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15505665198306

- # ====== Component Setting: NATIVE_IR ========================
  id: 204933187457651074617
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15505665198307

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 204933187774950074617
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15505665198307

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 204933188046785074617
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15505665198307

